version: "3.8"

services:
  mysqldbcatpro:
    container_name: mysqldbcatpro
    image: "mysql:8.0.23"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: catalogoprodutosdb      
    networks:
      catalogoprodutos-mysql-net:

  catalogoprodutos:
    container_name: catalogoprodutos
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - mysqldbcatpro
    networks:
      catalogoprodutos-mysql-net:
    restart: on-failure

networks:
  catalogoprodutos-mysql-net: